# Versions minimales recommandées pour les fonctionnalités modernes
android.compileSdk=34
android.minSdk=26
android.targetSdk=34

# Version du NDK nécessaire pour Oboe, TFLite, etc.
# Le CI/CD va utiliser cette version pour compiler votre code C++.
android.ndkVersion=26.1.10909125 

# Active la compilation Kotlin DSL (build.gradle.kts)
kotlin.code.style=official

# Enable AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=true
